FROM docker.io/golang:1.26.5 AS builder
COPY . src
RUN cd src && make bin


FROM docker.io/ubuntu:26.04@sha256:2260313b31c8c011cd2eebe728008efac1b3982be73eb71348ea2648d2c0e09b
LABEL maintainer="Dalton Hubble <dghubble@gmail.com>"
LABEL org.opencontainers.image.title="github-runner"
LABEL org.opencontainers.image.source="https://github.com/poseidon/github-runner"
LABEL org.opencontainers.image.vendor="Poseidon Labs"

ARG VERSION=2.335.1
ARG ARCH=arm64
ARG SHA=6d1e85bfd1a506a8b17c1f1b9b57dba458ffed90898799aaa9f599520b0d9207

COPY scripts /scripts
RUN /scripts/build

COPY --from=builder /go/src/bin/gha /opt/
WORKDIR /actions-runner
ENTRYPOINT ["/scripts/start"]

# Skip Github's script which interferes with signal handling.
CMD ["./bin/Runner.Listener", "run", "--startuptype", "service"]
