#!/usr/bin/env sh
# requires VERSION variable
# requires SHA variable
# requires ARCH variable
set -ex

# Avoid the tzdata prompt
export DEBIAN_FRONTEND=noninteractive

# base packages
# https://github.com/actions/runner/blob/main/docs/start/envlinux.md#full-dependencies-list
apt-get update
apt-get install --no-install-recommends -y \
  liblttng-ust-dev libkrb5-3 zlib1g libssl-dev libicu74 \
  git curl tar zip make dumb-init ca-certificates
apt-get clean

# Create a folder
mkdir actions-runner && cd actions-runner

# Download the runner bundle
curl -L https://github.com/actions/runner/releases/download/v${VERSION}/actions-runner-linux-${ARCH}-${VERSION}.tar.gz \
  -o runner.tar.gz
# Validate hash
echo "${SHA}  runner.tar.gz" | sha256sum -c
# Extract the installer
tar xzf ./runner.tar.gz
rm -f runner.tar.gz
