#!/usr/bin/dumb-init /bin/bash
set -e

export RUNNER_ALLOW_RUNASROOT=1

echo "Github Runner: $(./config.sh --version)"
echo "GH_APP_ID: ${GH_APP_ID}"
echo "GH_APP_KEY_PATH: ${GH_APP_KEY_PATH}"
echo "GH_APP_ID: ${GH_INSTALL_ID}"

fetch_token() {
  /opt/gha registration-token \
    --app-id "$GH_APP_ID" \
    --app-key-path "$GH_APP_KEY_PATH" \
    --install-id "$GH_INSTALL_ID" \
    --organization "$GH_ORG"
}

cleanup() {
  echo "Cleanup"
  ./config.sh remove --token "$(fetch_token)"
  exit
}

CONFIG_ARGS=(
  --url "https://github.com/${GH_ORG}"
  --token "$(fetch_token)"
  --runnergroup "${GROUP:-default}"
  --labels "${LABELS:-}"
  --work /runner
  --unattended
  --replace
  --disableupdate
)

case "${EPHEMERAL:-}" in
true | TRUE | 1 | yes | on | --ephemeral) CONFIG_ARGS+=(--ephemeral) ;;
esac

if [ -f "/actions-runner/.runner" ]; then
  echo "Already configured"
else
  echo "Configuring"
  ./config.sh "${CONFIG_ARGS[@]}"
fi

# deregister runner on interrupt
trap cleanup SIGINT SIGQUIT SIGTERM INT TERM QUIT

"$@"
